feat: _cmd() _clone()

diff --git a/xut b/xut
--- a/xut
+++ b/xut
@@ -39,6 +39,43 @@ msg() {
 	esac
 }
 
+# Commands with and without log
+_cmd() {
+	if [ "$op_log" = 0 ]; then
+		case "${1}" in
+			rm)       rm -f "${2}" ;;
+			rmd)      rm -fr "${2}" ;;
+			copy)     cp -Pr --remove-destination "${2}" "${3}" ;;
+			pull)     git pull -q origin ;;
+			branch)   git branch -q "${2}" ;;
+			switch)   git switch -mq "${2}" ;;
+			checkout) git checkout -q "${2}" ;;
+			checkR)   git -C "$conf_workdir/$default_repo_dir" checkout -q "${2}" ;;
+		esac
+	else
+		case "${1}" in
+			rm)       rm -fv "${2}" ;;
+			rmd)      rm -frv "${2}" ;;
+			copy)     cp -Pr --debug --remove-destination "${2}" "${3}" ;;
+			pull)     git pull origin ;;
+			branch)   git branch -v "${2}" ;;
+			switch)   git switch -m "${2}" ;;
+			checkout) git checkout "${2}" ;;
+			checkR)   git -C "$conf_workdir/$default_repo_dir" checkout "${2}" ;;
+		esac
+	fi
+}
+
+_clone() {
+	standard='"$repo" "$conf_workdir/$repodir"'
+	case "${1}" in
+		full)       git clone ${standard} ;;
+		normal)     git clone --depth 1 --no-single-branch ${standard} ;;
+		branch)     git clone -b "$branch" ${standard} ;;
+		fullBranch) git clone --depth 1 --no-single-branch -b "$branch" ${standard} ;;
+	esac
+}
+
 # Get the configuration from the conf file if it exists.
 
 #shellcheck disable=SC1091
@@ -149,6 +186,12 @@ have_branch() {
 	fi
 }
 
+create_template_list_for_repo() {
+	msg debug "Creating list of $repo templates"
+	dir=$(find_repodir "$repo")
+	find "$dir" -mindepth 1 -maxdepth 1 \( -type d -o -type l \) -exec basename {} \;
+}
+
 retrieve_repos() {
 	if [ "$op_retrieve" = 0 ]; then
 		msg debug "Not retrieving repos..."
@@ -169,18 +212,18 @@ retrieve_repos() {
 			if [ "$havebranch" = 'no' ]; then
 				if [ "$clone_history" = 'full' ]; then
 					msg info "Cloning $repo with full history..."
-					git clone "$repo" "$conf_workdir"/"$repodir" || msg error "Cannot clone $repo repo."
+					_clone full || msg error "Cannot clone $repo repo."
 				else
 					msg info "Cloning $repo..."
-					git clone --depth 1 --no-single-branch "$repo" "$conf_workdir"/"$repodir" || msg error "Cannot clone $repo repo."
+					_clone normal || msg error "Cannot clone $repo repo."
 				fi
 			elif [ "$havebranch" = 'yes' ]; then
 				if [ "$clone_history" = 'full' ]; then
 					msg info "Cloning $repo branch ${green}${branch}${R} with full history..."
-					git clone -b "$branch" "$repo" "$conf_workdir"/"$repodir" || msg error "Cannot clone $repo repo."
+					_clone branch || msg error "Cannot clone $repo repo."
 				else
 					msg info "Cloning $repo branch ${green}${branch}${R}..."
-					git clone --depth 1 --no-single-branch -b "$branch" "$repo" "$conf_workdir"/"$repodir" || msg error "Cannot clone $repo repo."
+					_clone fullbranch || msg error "Cannot clone $repo repo."
 				fi
 			else
 				msg error "Variable 'havebranch' badly defined !"
@@ -195,7 +238,7 @@ retrieve_repos() {
 	done
 
 	# Remove all not commited changes from the void-package clone
-	cd "$conf_workdir"/"$default_repo_dir" && git checkout .
+	cd "$conf_workdir"/"$default_repo_dir" && _cmd checkout .
 	op_sync=1
 }
 
@@ -210,21 +253,14 @@ sync_repos() {
 		find_repodir "$repo"
 		msg info "Syncing $repo..."
 		cd "$conf_workdir"/"$repodir" || msg error "Cannot change to $conf_workdir/$repodir"
-		current_branch=$(git branch --show-current 2>/dev/null)
+		current_branch=$(_cmd branch --show-current)
 		if [ "$repo" = "$default_repo" ] && [ "$current_branch" != "master" ]; then
-			git checkout master || msg error "Cannot switch to master branch. Probably uncommitted changes on $current_branch?"
+			_cmd checkout master || msg error "Cannot switch to master branch. Probably uncommitted changes on $current_branch?"
 			msg debug "Switched to master branch"
 		fi
 		# 'pull origin' to pull from same branch
-		if [ "$havebranch" = 'yes' ] ; then
-			git pull origin || msg error "Cannot sync to $repo"
-			msg info "Branch $branch from $repo ${green}synced${R}"
-			echo
-		else
-			git pull origin || msg error "Cannot sync to $repo"
-			msg info "$repo ${green}synced${R}"
-			echo
-		fi
+		_cmd pull || msg error "Cannot sync to $repo"
+		msg info "$repo ${green}synced${R}"
 	done
 	op_integrate=1
 }
@@ -257,6 +293,7 @@ should_copy_template() {
 	src_v=$(echo "$src_version" | tr -d '.')
 	dest_v=$(echo "$dest_version" | tr -d '.')
 
+	msg debug "Comparing: src(${src_version}_${src_revision}) vs dest(${dest_version}_${dest_revision})"
 	msg debug "Comparing: $source_template_name<src>(${src_version}_${src_revision}) vs $dest_template_name<dest>(${dest_version}_${dest_revision})"
 
 	# Compare versions
@@ -279,13 +316,8 @@ should_copy_template() {
 
 merge_xtra_templates() {
 	# First remove all templates lists
-	if [ "$op_log" = 0 ]; then
-		rm -f "$conf_workdir"/templates_*
-		rm -f "$conf_workdir"/*_templates
-	else
-		rm -v "$conf_workdir"/templates_* 2>/dev/null
-		rm -v "$conf_workdir"/*_templates 2>/dev/null
-	fi
+	_cmd rm "$conf_workdir"/templates_*
+	_cmd rm "$conf_workdir"/*_templates
 	# Merge all available template directories to a temporary directory,
 	# With intelligent version-based conflict resolution.
 	for repo in $repos_list; do
@@ -317,13 +349,11 @@ merge_xtra_templates() {
 				dest_template="$conf_workdir/$default_repo_dir/srcpkgs/$template_name/template"
 				if should_copy_template "$source_template" "$dest_template"; then
 					# Remove from merged_dir and copy template dir
-					if [ "$op_log" = 0 ]; then
-						[ -d "$merged_dir/$template_name" ] && rm -rf "${merged_dir:?}/$template_name"
-						cp -r "$dir" "$merged_dir" || msg error "Cannot merge templates"
-					else
-						[ -d "$merged_dir/$template_name" ] && rm -rfv "${merged_dir:?}/$template_name"
-						cp -rv "$dir" "$merged_dir" || msg error "Cannot merge templates"
-					fi
+
+					msg warn "Check and improve this!"
+					#[ -d "$merged_dir/$template_name" ] && _cmd rmd "${merged_dir:?}/$template_name" #bashism
+					[ -d "$merged_dir/$template_name" ] && _cmd rmd "$merged_dir/$template_name"
+					_cmd copy "$dir" "$merged_dir" || msg error "Cannot merge ${red}$template_name${R}"
 
 					# Extract commit metadata from source repository
 					cd "$conf_workdir/$repodir" || continue
@@ -355,10 +385,10 @@ merge_xtra_templates() {
 			done
 			printf "\n"
 		else
-			git -C "$conf_workdir/$default_repo_dir" checkout master
+			_cmd checkR master
 			# Include both directories and symlinks for void_templates
 			find "$conf_workdir/$default_repo_dir/srcpkgs" -mindepth 1 -maxdepth 1 \( -type d -o -type l \) -exec basename {} \; >"$conf_workdir"/void_templates
-			git -C "$conf_workdir/$default_repo_dir" checkout xut
+			_cmd checkR xut
 		fi
 	done
 	# Create template list for restricted packages, in order to include them in update discovery and updates.
@@ -367,13 +397,8 @@ merge_xtra_templates() {
 
 update_template_list() {
 	# First remove all templates lists
-	#if [ "$op_log" = 0 ]; then
-	#	rm -f "$conf_workdir"/templates_*
-	#	rm -f "$conf_workdir"/*_templates
-	#else
-	#	rm -v "$conf_workdir"/templates_* 2>/dev/null
-	#	rm -v "$conf_workdir"/*_templates 2>/dev/null
-	#fi
+	_cmd rm "$conf_workdir"/templates_*
+	_cmd rm "$conf_workdir"/*_templates
 	# Update all templates list
 	msg debug "Creating list of templates (This will take a while)"
 	all_templates=""
@@ -384,9 +409,9 @@ update_template_list() {
 	done
 	# Uniq and sort template lists
 	cat "$conf_workdir"/xtra_templates_source | sort -u >"$conf_workdir"/xtra_templates
-	rm -f "$conf_workdir"/xtra_templates_source
+	_cmd rm "$conf_workdir"/xtra_templates_source
 	cat "$conf_workdir"/all_templates_source | sort -u >"$conf_workdir"/all_templates
-	rm -f "$conf_workdir"/all_templates_source
+	_cmd rm "$conf_workdir"/all_templates_source
 	msg debug "Template merge completed."
 	msg info "
 	templates in void-packages: $(cat "$conf_workdir"/void_templates | wc -w)
@@ -413,14 +438,10 @@ integrate_xtra_templates() {
 			original_pkg="$conf_workdir/$default_repo_dir/srcpkgs/$pkg_name"
 			if [ -d "$original_pkg" ]; then
 				msg debug "Removing old package directory: $pkg_name"
-				rm -rf "$original_pkg" || msg error "Cannot remove $original_pkg"
+				_cmd rmd"$original_pkg" || msg error "Cannot remove $original_pkg"
 			fi
 		done
-		if [ "$op_log" = 0 ]; then
-			cp -r "$merged_dir"/* "$conf_workdir/$default_repo_dir/srcpkgs/" || msg error "Cannot copy templates to srcpkgs"
-		else
-			cp -rv "$merged_dir"/* "$conf_workdir/$default_repo_dir/srcpkgs/" || msg error "Cannot copy templates to srcpkgs"
-		fi
+		_cmd copy "$merged_dir"/* "$conf_workdir/$default_repo_dir/srcpkgs/" || msg error "Cannot copy templates to srcpkgs"
 		msg info "Templates copied into $default_repo_dir branch ${green}xut${R}"
 	else
 		msg info "No new or updated templates to merge"
@@ -444,17 +465,17 @@ integrate_xtra_templates() {
 	}
 
 	# Switch to or create merge branch
-	current_branch=$(git branch --show-current)
+	current_branch=$(_cmd branch --show-current)
 	if [ "$current_branch" != "$merge_branch" ]; then
 		msg info "Switching to '$merge_branch' branch"
 
 		# Try to switch to existing branch, create if it doesn't exist
-		if ! git switch -mq "$merge_branch" 2>/dev/null; then
-			git branch "$merge_branch" || {
+		if ! _cmd switch "$merge_branch"; then
+			_cmd branch "$merge_branch" || {
 				msg error "Cannot create branch: $merge_branch"
 				return 1
 			}
-			git switch -q "$merge_branch" || {
+			_cmd switch "$merge_branch" || {
 				msg error "Cannot switch to branch: $merge_branch"
 				return 1
 			}
@@ -478,20 +499,20 @@ integrate_xtra_templates() {
 
 		if [ -f "$merged_pkg/.xut_commit_meta" ]; then
 			. "$merged_pkg/.xut_commit_meta"
-			rm -f "$merged_pkg/.xut_commit_meta"
+			_cmd rm "$merged_pkg/.xut_commit_meta"
 		fi
 
 		# Remove old package directory if exists
 		if [ -d "$original_pkg" ]; then
 			msg debug "Removing old package directory: $pkg_name"
-			rm -rf "$original_pkg" || {
+			_cmd rmd "$original_pkg" || {
 				msg error "Cannot remove $original_pkg"
 				return 1
 			}
 		fi
 
 		# Copy new package
-		cp -rL "$merged_pkg" "$conf_workdir/$default_repo_dir/srcpkgs/" || {
+		_cmd copy "$merged_pkg" "$conf_workdir/$default_repo_dir/srcpkgs/" || {
 			msg error "Cannot copy package $pkg_name to srcpkgs"
 			return 1
 		}
