feat: have_branch()

diff --git a/xut b/xut
--- a/xut
+++ b/xut
@@ -174,6 +174,18 @@ create_template_list_for_repo() {
 	find "$dir" -mindepth 1 -maxdepth 1 \( -type d -o -type l \) -exec basename {} \;
 }
 
+have_branch() {
+	if [ "${repo}" != "${repo%@*}" ]; then
+		branch=$(echo "$repo" | cut -d'@' -f2)
+		msg debug "Using custom $branch branch"
+		repo=$(echo "$repo" | cut -d'@' -f1)
+		havebranch=yes
+	else
+		havebranch=no
+		msg debug "Using standard branch"
+	fi
+}
+
 retrieve_repos() {
 	if [ "$op_retrieve" = 0 ]; then
 		msg debug "Not retrieving repos..."
@@ -182,11 +194,20 @@ retrieve_repos() {
 	# Clone every configured repo if needed.
 	msg info "Cloning repos..."
 	for repo in $repos_list; do
+		have_branch
 		find_repodir "$repo"
 		if [ ! -d "$conf_workdir"/"$repodir" ]; then
 			op_changed=1
-			msg debug "Cloning $repo..."
-			git clone --depth 1 "$repo" "$conf_workdir"/"$repodir" || msg error "Cannot clone $repo repo."
+			if [ "$havebranch" = 'no' ]; then
+				msg debug "Cloning $repo..."
+				git clone --depth 1 "$repo" "$conf_workdir"/"$repodir" || msg error "Cannot clone $repo repo."
+			elif [ "$havebranch" = 'yes' ]; then
+				msg debug "Cloning $repo branch $branch"
+				git clone --depth 1 -b "$branch" "$repo" "$conf_workdir"/"$repodir" || msg error "Cannot clone $branch branch of $repo repo."
+			else
+				msg error "Variable 'havebranch' badly defined!"
+				exit 1
+			fi
 			msg debug "Successfully cloned $repo !"
 			msg info "Creating templates list"
 			create_template_list_for_repo
@@ -208,6 +229,7 @@ sync_repos() {
 	fi
 	msg info "Syncing repos..."
 	for repo in $repos_list; do
+		have_branch
 		find_repodir "$repo"
 		msg debug "Syncing $repo..."
 		cd "$conf_workdir"/"$repodir" || msg error "Cannot change to $conf_workdir/$repodir"
@@ -217,7 +239,11 @@ sync_repos() {
 			msg debug "Switched to master branch"
 		fi
 		git pull "$repo" || msg error "Cannot sync to $repo"
-		msg info "$repo synced"
+		if [ "$havebranch" = 'yes' ] ; then
+			msg info "Branch $branch from $repo synced"
+		else
+			msg info "$repo synced"
+		fi
 	done
 	op_integrate=1
 }
@@ -282,6 +308,7 @@ merge_xtra_templates() {
 	# Merge all available template directories to a temporary directory,
 	# With intelligent version-based conflict resolution.
 	for repo in $repos_list; do
+		have_branch
 		find_repodir "$repo"
 		if [ "$repo" != "$default_repo" ]; then
 			msg info "Merging templates from ${green}${bold}$repo${reset_colour}"
