chore: xut formatting

diff --git a/xut b/xut
--- a/xut
+++ b/xut
@@ -23,9 +23,20 @@ root_check() {
 set_colours() {
 	# Set colour codes and provide fallback
 	if command -v tput >/dev/null 2>&1 && [ -z "${NO_COLOR+x}" ] && [ -t 0 ]; then # make tput(1) optional, respect $NO_COLOR
-		green=$(tput setaf 2);red=$(tput setaf 1);yellow=$(tput setaf 3)
-		fade=$(tput dim);bold=$(tput bold);resetColour=$(tput sgr0)
-	else green="";red="";yellow="";fade="";bold="";resetColour="";fi
+		green=$(tput setaf 2)
+		red=$(tput setaf 1)
+		yellow=$(tput setaf 3)
+		fade=$(tput dim)
+		bold=$(tput bold)
+		resetColour=$(tput sgr0)
+	else
+		green=""
+		red=""
+		yellow=""
+		fade=""
+		bold=""
+		resetColour=""
+	fi
 }
 
 set_default_vars() {
@@ -33,15 +44,15 @@ set_default_vars() {
 	xutVersion=0.4.2
 	readonly xutVersion
 
-	opLog=0       #Controls the appearance of debug messages for the user (-l)
-	opQuery=0     #Search for templates (-q)
-	opBuild=0     #Build packages, ( -b).
-	opInstall=0   #Install packages (-i <package1,package2>)
-	opXbpsSrc="" #Contains the xbps-src command to be given after the -x argument
-	opUpdate=0    #Update sw from updated templates (-u)
-	opSync=0      #Sync repos
-	opIntegrate=0 #Intergrate all templates into a merged repo.
-	opForeignHost=0	#Detection of non-Voidlinux host system.
+	opLog=0         # Controls the appearance of debug messages for the user (-l)
+	opQuery=0       # Search for templates (-q)
+	opBuild=0       # Build packages, ( -b).
+	opInstall=0     # Install packages (-i <package1,package2>)
+	opXbpsSrc=""    # Contains the xbps-src command to be given after the -x argument
+	opUpdate=0      # Update sw from updated templates (-u)
+	opSync=0        # Sync repos
+	opIntegrate=0   # Intergrate all templates into a merged repo.
+	opForeignHost=0 # Detection of non-Voidlinux host system.
 
 	# Initialise empty vars
 	templatesToUpdate=""
@@ -53,7 +64,9 @@ distribution_sanity_check() {
 	#shellcheck disable=SC1091
 	[ -r /etc/os-release ] && . /etc/os-release
 	if [ -z "$NAME" ] || [ "$NAME" != "Void" ]; then
-		opUpdate=0; opInstall=0; opForeignHost=1
+		opUpdate=0
+		opInstall=0
+		opForeignHost=1
 		msg info "[xut] is not running under Void Linux. Install and update operations are disabled."
 	else
 		msg debug "Running on Void linux, all systems go!"
@@ -64,7 +77,8 @@ msg() {
 	# Use colour-coded messages for informational, warning, and error output ${1} is the message type,
 	# ${2} is the message content needs to be here, all messages depend on it.
 	if [ "${1}" = "error" ]; then
-		printf "%s\n" "${red}${bold}(!!) Error:${resetColour} ${bold}${2}${resetColour}" ; exit 1
+		printf "%s\n" "${red}${bold}(!!) Error:${resetColour} ${bold}${2}${resetColour}"
+		exit 1
 	elif [ "${1}" = "warn" ]; then
 		printf "%s\n" "${yellow}${bold}(~~) Warning:${resetColour} ${bold}${2} ${resetColour}"
 	elif [ "${1}" = "info" ]; then
@@ -72,7 +86,8 @@ msg() {
 	elif [ "${1}" = "debug" ]; then
 		[ "$opLog" -eq 1 ] && printf "%s\n" "${fade}(<>) Debug : ${2} ${resetColour}"
 	else
-		printf "%s\n" "${red}(!!) Error: ${1} is not recognised for msg() ${resetColour}" ; exit 1
+		printf "%s\n" "${red}(!!) Error: ${1} is not recognised for msg() ${resetColour}"
+		exit 1
 	fi
 }
 
@@ -94,9 +109,14 @@ set_default_configuration() {
 	readonly defaultRepo
 	repoAbyssPackages=https://codeberg.org/mobinmob/abyss-packages
 	readonly repoAbyssPackages
-	defaultRepoDir=$(rdlast="${defaultRepo%/}"; rdfirst="${rdlast%/*}"; printf '_%s_%s\n' "${rdfirst##*/}" "${rdlast##*/}")
+	defaultRepoDir=$(
+		rdlast="${defaultRepo%/}"
+		rdfirst="${rdlast%/*}"
+		printf '_%s_%s\n' "${rdfirst##*/}" "${rdlast##*/}"
+	)
 	readonly defaultRepoDir
-	[ -n "$CONF_WORKDIR" ] && confWorkdir="$CONF_WORKDIR" && msg info "Using $confWorkdir as working directory."
+	[ -n "$CONF_WORKDIR" ] && confWorkdir="$CONF_WORKDIR" &&
+		msg info "Using $confWorkdir as working directory."
 	[ -z "$confWorkdir" ] && confWorkdir="$HOME"/.xut
 
 	# Define a log filename
@@ -106,29 +126,34 @@ set_default_configuration() {
 	# Check for needed dirs.
 	[ ! -e "$confLogDir" ] && mkdir -p "$confLogDir"
 	readonly logFile
-	XUT_TMP="${XUT_TMPDIR:-/tmp}/xut_tmp" # Use tmpfs for hotspots, adjust if user has XUT_TMPDIR set.
+	# Use tmpfs for hotspots, adjust if user has XUT_TMPDIR set.
+	XUT_TMP="${XUT_TMPDIR:-/tmp}/xut_tmp"
 	templatesCache="$XUT_TMP/templates"
-	mkdir -p "$XUT_TMP/templates" || msg error "Cannot create tmpfs workspace $XUT_TMP/templates"
+	mkdir -p "$XUT_TMP/templates" ||
+		msg error "Cannot create tmpfs workspace $XUT_TMP/templates"
 	# Merged templates directory
-	mergedDir=$(mktemp -d "${XUT_TMPDIR:-/tmp}/merged.XXXXXX") || msg error "Cannot create $mergedDir"
+	mergedDir=$(mktemp -d "${XUT_TMPDIR:-/tmp}/merged.XXXXXX") ||
+		msg error "Cannot create $mergedDir"
 	# Cleanup on exit
 	trap '[ -n "$mergedDir" ] && rm -rf "$mergedDir" "$XUT_TMP/templates"' EXIT INT TERM
 }
 
 usage() {
-	# Display basic tui information
+	# Display logo
 	printf "%s\n" "${green}${bold}
             _
 __  ___   _| |_
 \ \/ / | | | __|
  >  <| |_| | |_
 /_/\_\\__,_|\__| ${resetColour}"
-printf "%s\n" "${yellow}${bold}
+	# Display basic tui information
+	printf "%s\n" "${yellow}${bold}
 *x*tra *u*ser *t*emplates
 Build and install packages for Void Linux, from unofficial abyss-packages template repo.
 Version: $xutVersion
 Usage: xut [options] ${resetColour}"
-printf "%s\n" "${bold}
+	# Display OPTIONS
+	printf "%s\n" "${bold}
 OPTIONS
  -s                      Sync the repos.
  -l                      Keep a log file under $confLogDir.
@@ -147,7 +172,11 @@ OPTIONS
 
 find_repodir() {
 	# Define a proper (no slashes...) directory name for a remote git repo
-	repodir=$(rdlast="${1%/}"; rdfirst="${rdlast%/*}"; printf '_%s_%s\n' "${rdfirst##*/}" "${rdlast##*/}")
+	repodir=$(
+		rdlast="${1%/}"
+		rdfirst="${rdlast%/*}"
+		printf '_%s_%s\n' "${rdfirst##*/}" "${rdlast##*/}"
+	)
 }
 
 create_template_list() {
@@ -155,20 +184,20 @@ create_template_list() {
 	# ${1} and stores it in ${2}. Checks if dirs contain template files.
 	msg debug "Creating template list for ${1} in ${2}..."
 	dir="$1"
-    out="$2"
-    [ -d "$dir" ] || msg error "Directory $dir does not exist!"
-    : > "$out"
-    # Loop over possible template files
-    for tpl in "$dir"/*/template; do
-        [ -f "$tpl" ] || continue
-        pkgdir="${tpl%/template}"
-        printf "%s\n" "${pkgdir##*/}" >> "$out"
-    done
+	out="$2"
+	[ -d "$dir" ] || msg error "Directory $dir does not exist!"
+	: >"$out"
+	# Loop over possible template files
+	for tpl in "$dir"/*/template; do
+		[ -f "$tpl" ] || continue
+		pkgdir="${tpl%/template}"
+		printf "%s\n" "${pkgdir##*/}" >>"$out"
+	done
 }
 
 extract_verrev() {
 	# Get version_revision from ${1}
-    awk -F= '
+	awk -F= '
         /version=/ {
             ver=$2
             gsub(/"/,"",ver)
@@ -187,9 +216,9 @@ include_additional_repos() {
 	#shellcheck disable=SC2154
 	for xtraRepo in $additionalRepos; do
 		case "$xtraRepo" in
-            http://*|https://*) ;;
-            *)
-                msg error "Invalid repo entry: '$xtraRepo'
+			http://* | https://*) ;;
+			*)
+				msg error "Invalid repo entry: '$xtraRepo'
 Each repo must be a URL beginning with http:// or https://
 Fix your 'additionalRepos' configuration."
                 ;;
@@ -205,7 +234,8 @@ retrieve_repos() {
 		find_repodir "$repo"
 		if [ ! -d "$confWorkdir/$repodir"/.git ]; then
 			msg debug "Cloning $repo..."
-			git clone --depth 1 "$repo" "$confWorkdir/$repodir" || msg error "Cannot clone $repo repo."
+			git clone --depth 1 "$repo" "$confWorkdir/$repodir" ||
+				msg error "Cannot clone $repo repo."
 			msg debug "Successfully cloned $repo !"
 			opIntegrate=1
 		else
@@ -222,9 +252,10 @@ sync_repos() {
 		msg debug "Syncing $repo..."
 		currentBranch=$(git -C "$confWorkdir/$repodir" symbolic-ref --short HEAD 2>/dev/null)
 		default_branch=$(git -C "$confWorkdir/$repodir" symbolic-ref --short refs/remotes/origin/HEAD | sed 's|origin/||') # that is not 100% correct, should fix
-		git -C "$confWorkdir/$repodir" checkout "$default_branch" || msg error "Cannot switch to $default_branch. Probably uncommitted changes on $currentBranch?"
+		git -C "$confWorkdir/$repodir" checkout "$default_branch" ||
+			msg error "Cannot switch to $default_branch. Probably uncommitted changes on $currentBranch?"
 		msg debug "Switched to $default_branch"
-		git -C "$confWorkdir/$repodir" pull "$repo"  || msg error "Cannot sync to $repo"
+		git -C "$confWorkdir/$repodir" pull "$repo" || msg error "Cannot sync to $repo"
 		msg info "$repo synced"
 	done
 	opIntegrate=1
@@ -265,13 +296,13 @@ merge_xtra_templates() {
 		find_repodir "$repo"
 		repoName="${repo##*/}"
 		if [ "$repo" = "$defaultRepo" ]; then
-			default_branch=$(git -C "$confWorkdir/$repodir" symbolic-ref --short refs/remotes/origin/HEAD \
-			 | sed 's|origin/||')
-			git -C "$confWorkdir/$repodir" checkout "$default_branch" \
-			 || msg error "Cannot switch to $default_branch. Probably uncommitted changes on $currentBranch?"
+			default_branch=$(git -C "$confWorkdir/$repodir" symbolic-ref --short refs/remotes/origin/HEAD |
+				sed 's|origin/||')
+			git -C "$confWorkdir/$repodir" checkout "$default_branch" ||
+				msg error "Cannot switch to $default_branch. Probably uncommitted changes on $currentBranch?"
 			# Create template lists from a clean checkout.
-			git -C  "$confWorkdir/$repodir" clean -fd > /dev/null 2>&1 || msg error "Cannot clean $confWorkdir/$repodir repo."
-			xbps-checkvers -s -D "$confWorkdir/$defaultRepoDir" -f %n | sort > "$templatesCache"/void_templates
+			git -C "$confWorkdir/$repodir" clean -fd >/dev/null 2>&1 || msg error "Cannot clean $confWorkdir/$repodir repo."
+			xbps-checkvers -s -D "$confWorkdir/$defaultRepoDir" -f %n | sort >"$templatesCache"/void_templates
 			# Create template list for restricted packages, in order to include them in update discovery and updates.
 			grep -lr "restricted=yes" "$confWorkdir/$defaultRepoDir/srcpkgs/" | awk -F '/' '{print $(NF-1)}' >"$templatesCache/templates_restricted-packages"
 		else
@@ -288,7 +319,7 @@ merge_xtra_templates() {
 			# Process templates
 			find "$searchPath" -maxdepth 2 -type f -name template | while IFS= read -r template; do
 				[ -f "$template" ] || continue
-    			dir="${template%/template}"
+				dir="${template%/template}"
 				processed=$((processed + 1))
 				printf "\r%5d " "$processed"
 				templateName="${dir##*/}"
@@ -305,34 +336,33 @@ merge_xtra_templates() {
 	done
 }
 
-
 generate_all_template_lists() {
-    msg info "Generating template lists..."
+	msg info "Generating template lists..."
 
-    # Ensure template merge has happened
-    [ -r "$templatesCache/templates_restricted-packages" ] || merge_xtra_templates
+	# Ensure template merge has happened
+	[ -r "$templatesCache/templates_restricted-packages" ] || merge_xtra_templates
 
-    # --- xtra template list (merging templates_*) ---
-    xtra="$templatesCache/xtra_templates"
-    : >"$xtra"
+	# --- xtra template list (merging templates_*) ---
+	xtra="$templatesCache/xtra_templates"
+	: >"$xtra"
 
-    for file in "$templatesCache"/templates_*; do
-        [ -r "$file" ] && cat "$file" >>"$xtra"
-    done
+	for file in "$templatesCache"/templates_*; do
+		[ -r "$file" ] && cat "$file" >>"$xtra"
+	done
 
-    # unique + sorted (portable)
+	# unique + sorted (portable)
 	tmp=$(mktemp) || msg error "Failed to create temp file"
-    sort -u "$xtra" >"$tmp"
-    mv "$tmp" "$xtra"
+	sort -u "$xtra" >"$tmp"
+	mv "$tmp" "$xtra"
 
-    msg debug "Template merge completed."
-    msg info "templates in void-packages: ${green}$(wc -l < "$templatesCache"/void_templates)${resetColour}"
-    msg info "restricted templates: ${green}$(wc -l < "$templatesCache"/templates_restricted-packages) ${resetColour}"
-    for repo in $reposList; do
+	msg debug "Template merge completed."
+	msg info "templates in void-packages: ${green}$(wc -l <"$templatesCache"/void_templates)${resetColour}"
+	msg info "restricted templates: ${green}$(wc -l <"$templatesCache"/templates_restricted-packages) ${resetColour}"
+	for repo in $reposList; do
 		find_repodir "$repo"
 		if [ "$repo" != "$defaultRepo" ]; then
 			repoName="${repo##*/}"
-			msg info "Templates in $repoName: ${green}$(wc -l < "$templatesCache"/templates_"$repoName") ${resetColour}"
+			msg info "Templates in $repoName: ${green}$(wc -l <"$templatesCache"/templates_"$repoName") ${resetColour}"
 		fi
 	done
 }
@@ -406,16 +436,14 @@ discover_updates() {
 	#Build list of templates to be updated
 	toBeUpdated="$templatesCache/toBeUpdated"
 	: >"$toBeUpdated"
-	xbps-checkvers -I -D "$confWorkdir/$defaultRepoDir/" -f %n \
-     >"$toBeUpdated"
+	xbps-checkvers -I -D "$confWorkdir/$defaultRepoDir/" -f %n >"$toBeUpdated"
 	tmp2=$(mktemp)
 	sort -u "$toBeUpdated" >"$tmp2"
 	mv "$tmp2" "$toBeUpdated"
 	# Intersection of sorted lists (comm requires sorting)
-	comm -1 -2 "$toBeUpdated" "$xtraTemplatesFile" \
-     >"$templatesCache/templatesToUpdate"
+	comm -1 -2 "$toBeUpdated" "$xtraTemplatesFile" >"$templatesCache/templatesToUpdate"
 	# Convert file into space-separated list
-	templatesToUpdate=$(tr '\n' ' ' < "$templatesCache/templatesToUpdate")
+	templatesToUpdate=$(tr '\n' ' ' <"$templatesCache/templatesToUpdate")
 	export templatesToUpdate
 }
 
@@ -473,8 +501,8 @@ build_packages() {
 	if [ -n "$packages" ] && [ "$opInstall" = 0 ]; then
 		msg info "Successfully build $packages!"
 		msg info "Packages are in $confWorkdir/$defaultRepoDir/hostdir/."
-		[ "$opForeignHost" != 1 ] \
-			&& msg info "You can install them with xbps or by running <xut -i>."
+		[ "$opForeignHost" != 1 ] &&
+			msg info "You can install them with xbps or by running <xut -i>."
 		exit 0
 	fi
 }
@@ -510,7 +538,8 @@ root_check
 
 # Keep at least 5 log files, including the current one.
 find "$confLogDir" -name "xut_*.log" | sort -r | awk 'NR>5 {print}' | while IFS= read -r file; do
-    rm -f "$file"; done
+	rm -f "$file"
+done
 
 # Capture all the arguments given
 showargs="$(printf "%s" "$*")"
@@ -519,20 +548,41 @@ while getopts "slhudb:i:x:q:" OPTION; do
 	case "${OPTION}" in
 		s) opSync=1 ;;
 		l) opLog=1 ;;
-		d) opLog=1; set -x ;;
-		b) packages="$OPTARG"; opBuild=1 ;;
-		i) packages="$OPTARG"; opInstall=1 ;;
-		x) opXbpsSrc="$OPTARG"; xbps_src_command ;;
-		q) templateQuery="$OPTARG"; opQuery=1 ;;
+		d)
+			opLog=1
+			set -x
+			;;
+		b)
+			packages="$OPTARG"
+			opBuild=1
+			;;
+		i)
+			packages="$OPTARG"
+			opInstall=1
+			;;
+		x)
+			opXbpsSrc="$OPTARG"
+			xbps_src_command
+			;;
+		q)
+			templateQuery="$OPTARG"
+			opQuery=1
+			;;
 		u) opUpdate=1 ;;
-		h) usage ; exit 0;;
-		*) usage ; exit 1;;
+		h)
+			usage
+			exit 0
+			;;
+		*)
+			usage
+			exit 1
+			;;
 	esac
 done
 shift $((OPTIND - 1))
 # Check for empty args
-[ "$OPTIND" -eq 1 ] && usage && \
- msg warn "Nothing to do, please provide an argument!
+[ "$OPTIND" -eq 1 ] && usage &&
+	msg warn "Nothing to do, please provide an argument!
 		See OPTIONS above." && exit 1
 if [ "$opLog" -eq 1 ]; then
 	main 2>&1 | tee "$logFile"
