chore: colors case + R instead of reset_colours

diff --git a/xut b/xut
--- a/xut
+++ b/xut
@@ -20,24 +20,23 @@ msg() {
 	# ${2} is the message content needs to be here, all messages depend on it.
 
 	# Colours
-	green=$(tput setaf 2)
 	red=$(tput setaf 1)
+	green=$(tput setaf 2)
 	yellow=$(tput setaf 3)
+	blue=$(tput setaf 4)
+	pink=$(tput setaf 5)
+	gray=$(tput setaf 8)
 	fade=$(tput dim)
 	bold=$(tput bold)
-	reset_colour=$(tput sgr0)
+	R=$(tput sgr0)
 
-	if [ "${1}" = "error" ]; then
-		printf "%s\n" "${red}${bold}(!!) Error:${reset_colour} ${bold}${2}${reset_colour}" && exit 1
-	elif [ "${1}" = "warn" ]; then
-		printf "%s\n" "${yellow}${bold}(~~) Warning:${reset_colour} ${bold}${2} ${reset_colour}"
-	elif [ "${1}" = "info" ]; then
-		printf "%s\n" "${green}${bold}(~>) Info:${reset_colour}  ${bold}${2} ${reset_colour}"
-	elif [ "${1}" = "debug" ]; then
-		[ "$op_log" = 1 ] && printf "%s\n" "$fade(<>) Debug : ${2} ${reset_colour}"
-	else
-		printf "%s\n" "${red}(!!) Error: ${1} is not recognised for msg() ${reset_colour}" && exit 1
-	fi
+	case "${1}" in
+		debug) [ "$op_log" = 1 ] && printf "%s\n" "$fade(<>) Debug : ${2} ${R}" ;;
+		error) printf "%s\n" "${red}${bold}(!!) Error:${R} ${bold}${2}${R}" && exit 1 ;;
+		 warn) printf "%s\n" "${yellow}${bold}(~~) Warning:${R} ${bold}${2} ${R}" ;;
+		 info) printf "%s\n" "${green}${bold}(~>) Info:${R}  ${bold}${2} ${R}" ;;
+		    *) printf "%s\n" "${red}(!!) Error: ${1} is not recognised for msg() ${R}" && exit 1 ;;
+	esac
 }
 
 # Get the configuration from the conf file if it exists.
@@ -169,10 +168,10 @@ retrieve_repos() {
 				fi
 			elif [ "$havebranch" = 'yes' ]; then
 				if [ "$clone_history" = 'full' ]; then
-					msg info "Cloning $repo branch ${green}${branch}${reset_colour} with full history..."
+					msg info "Cloning $repo branch ${green}${branch}${R} with full history..."
 					git clone -b "$branch" "$repo" "$conf_workdir"/"$repodir" || msg error "Cannot clone $repo repo."
 				else
-					msg info "Cloning $repo branch ${green}${branch}${reset_colour}..."
+					msg info "Cloning $repo branch ${green}${branch}${R}..."
 					git clone --depth 1 --no-single-branch -b "$branch" "$repo" "$conf_workdir"/"$repodir" || msg error "Cannot clone $repo repo."
 				fi
 			else
@@ -206,13 +205,14 @@ sync_repos() {
 			git checkout master || msg error "Cannot switch to master branch. Probably uncommitted changes on $current_branch?"
 			msg debug "Switched to master branch"
 		fi
+		# pull origin to pull from same branch
 		if [ "$havebranch" = 'yes' ] ; then
 			git pull origin || msg error "Cannot sync to $repo"
-			msg info "Branch $branch from $repo synced"
+			msg info "Branch $branch from $repo ${green}synced${R}"
 			echo
 		else
 			git pull origin || msg error "Cannot sync to $repo"
-			msg info "$repo synced"
+			msg info "$repo ${green}synced${R}"
 			echo
 		fi
 	done
@@ -251,7 +251,7 @@ should_copy_template() {
 
 	# Compare versions
 	if [ "$src_v" -gt "$dest_v" ] 2>/dev/null; then
-		msg info "newer ${green}${bold}$template_name${reset_colour} version"
+		msg info "newer ${green}${bold}$template_name${R} version"
 		op_changed=1
 		return 0
 	elif [ "$src_v" -lt "$dest_v" ] 2>/dev/null; then
@@ -260,7 +260,7 @@ should_copy_template() {
 
 	# Versions equal, compare revision
 	if [ "$src_revision" -gt "$dest_revision" ] 2>/dev/null; then
-		msg info "newer ${green}${bold}$template_name${reset_colour} revision"
+		msg info "newer ${green}${bold}$template_name${R} revision"
 		op_changed=1
 		return 0
 	fi
@@ -282,7 +282,7 @@ merge_xtra_templates() {
 		have_branch
 		find_repodir "$repo"
 		if [ "$repo" != "$default_repo" ]; then
-			msg info "Merging templates from ${green}${bold}$repo${reset_colour}"
+			msg info "Merging templates from ${green}${bold}$repo${R}"
 			search_path="$conf_workdir/$repodir"
 			if [ -d "$conf_workdir/$repodir/srcpkgs" ]; then
 				search_path="$conf_workdir/$repodir/srcpkgs"
@@ -347,7 +347,7 @@ update_template_list() {
 	msg info "
 	templates in void-packages: $(cat "$conf_workdir"/void_templates | wc -w)
 	xtra_templates: $(cat "$conf_workdir"/xtra_templates | wc -w) (Not unique)
-	Available templates: ${green}${bold}$(cat "$conf_workdir"/all_templates | wc -w)${reset_colour}
+	Available templates: ${green}${bold}$(cat "$conf_workdir"/all_templates | wc -w)${R}
 	"
 }
 
@@ -411,9 +411,9 @@ search_templates() {
 				templates_*) file_name=$(echo "$file_name" | cut -d'_' -f2) ;;
 				void_templates) file_name="void-packages" ;;
 			esac
-			msg info "Found in ${green}${bold}$file_name${reset_colour}:"
+			msg info "Found in ${green}${bold}$file_name${R}:"
 			grep "$template_query" "$file" | while read -r line; do
-				printf "%s\n" "  ${green}(*)${reset_colour} ${bold}${line}${reset_colour}"
+				printf "%s\n" "  ${green}(*)${R} ${bold}${line}${R}"
 			done
 		fi
 	done
@@ -516,7 +516,7 @@ install_packages() {
 main() {
 	# Check for root
 	[ "$(id -u)" = 0 ] && msg error "Please run the program as a user!"
-	msg info "Full command given is [xut $showargs]."
+	msg info "Full command given is [${green}xut $showargs${R}]."
 	[ -n "$op_xbps_src" ] && xbps_src_command
 	include_additional_repos
 
